services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - ./db:/data/db   # Mount the volume to persist MongoDB data