services:
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    command: bash -c "mongod --fork --logpath /var/log/mongodb.log && mongorestore /dump && tail -f /var/log/mongodb.log"
    volumes:
      - ./dump:/dump   # Mount the dump folder to /dump in the container
      - .:/app